# NOTE: Generated By hrp v4.3.8-202401091556, DO NOT EDIT!

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from debugtalk import *


if __name__ == "__main__":
    import funppy
    funppy.register("get_user_agent", get_user_agent)
    funppy.serve()
